apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
    - port: 8080
      targetPort: 8080

--- 

apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: nginx
spec:
  volumes:
  - name: tls
    secret:
      secretName: tls-config
  - name: app-config
    configMap:
      name: nginx-config
  containers:
  - name: nginx
    image: nginx
    ports: 
    - containerPort: 80
    volumeMounts:
    - name: app-config
      mountPath: /etc/nginx/conf.d
    - name: tls
      mountPath: /etc/nginx/tls
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
