apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-replicaset
  template:
    metadata:
      labels: 
        app: myapp-replicaset
    spec:
      containers:
      - name: my-app
        image: yoonjeong/my-app:2.0-unhealthy
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"

